[project]
name = "evita-material-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "myst-nb>=1.3.0",
    "sphinx>=8.2.3",
    "sphinx-evita>=0.1.0b1",
    "sphinx-lesson>=0.8.16",
    "sphinxcontrib-bibtex>=2.6.5",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.4.6",
    "jupyterlab-myst>=2.4.2",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "scipy>=1.16.1",
]
